/* ─── PROCUREMENT ANALYTICS ──────────────────────────────────────────
   Computes reorder planning, sales velocity, ABC analysis, and stock
   health from Shopify inventory + orders data.
   All monetary values are in the store's native currency.
──────────────────────────────────────────────────────────────────── */

/* ─── VELOCITY ────────────────────────────────────────────────────── */

// Returns units sold per day for `sku` in the last `days` days
export function calcSalesVelocity(orders, sku, days = 30) {
  const normalSku = sku.trim().toUpperCase();
  const cutoffMs  = Date.now() - days * 86400000;
  let total = 0;
  for (const o of orders) {
    if (o.cancelled_at) continue;
    if (new Date(o.created_at).getTime() < cutoffMs) continue;
    for (const item of o.line_items || []) {
      if ((item.sku || '').trim().toUpperCase() === normalSku) {
        total += parseInt(item.quantity) || 0;
      }
    }
  }
  return total / days; // units per day
}

// Revenue generated by `sku` in the last `days` days
export function calcSkuRevenue(orders, sku, days = 30) {
  const normalSku = sku.trim().toUpperCase();
  const cutoffMs  = Date.now() - days * 86400000;
  let total = 0;
  for (const o of orders) {
    if (o.cancelled_at) continue;
    if (new Date(o.created_at).getTime() < cutoffMs) continue;
    for (const item of o.line_items || []) {
      if ((item.sku || '').trim().toUpperCase() === normalSku) {
        total += (parseFloat(item.price) || 0) * (parseInt(item.quantity) || 0);
      }
    }
  }
  return total;
}

/* ─── DAYS OF INVENTORY ───────────────────────────────────────────── */

// Returns DOI (days of stock left at current velocity). 999 = no sales / infinite.
export function calcDaysOfInventory(currentStock, velocityPerDay) {
  if (velocityPerDay <= 0) return currentStock > 0 ? 999 : 0;
  return Math.floor(currentStock / velocityPerDay);
}

/* ─── STOCK HEALTH ────────────────────────────────────────────────── */

export function classifyStockHealth(doi, stock) {
  if (stock === 0 || doi === 0) return 'stockout';
  if (doi < 14) return 'critical';
  if (doi < 30) return 'low';
  if (doi < 90) return 'healthy';
  return 'overstock';
}

export const HEALTH_META = {
  stockout:  { label: 'Stockout',  color: '#ef4444', bg: 'bg-red-500/10',    text: 'text-red-400',   ring: 'ring-red-500/30'   },
  critical:  { label: 'Critical',  color: '#f97316', bg: 'bg-orange-500/10', text: 'text-orange-400',ring: 'ring-orange-500/30' },
  low:       { label: 'Low',       color: '#eab308', bg: 'bg-yellow-500/10', text: 'text-yellow-400',ring: 'ring-yellow-500/30' },
  healthy:   { label: 'Healthy',   color: '#22c55e', bg: 'bg-emerald-500/10',text: 'text-emerald-400',ring: 'ring-emerald-500/30'},
  overstock: { label: 'Overstock', color: '#6366f1', bg: 'bg-violet-500/10', text: 'text-violet-400', ring: 'ring-violet-500/30' },
};

/* ─── REORDER PLANNING ────────────────────────────────────────────── */

// Returns the recommended reorder quantity for a SKU.
// EOQ = Economic Order Quantity (simplified Wilson formula).
export function calcReorderQty(velocity30, moq = 0, leadTimeDays = 14, restockDays = 45) {
  const needed = velocity30 * restockDays; // stock needed to cover restock period
  return Math.max(moq, Math.ceil(needed));
}

// Reorder Point: when current stock hits this level, place an order NOW
export function calcReorderPoint(velocity30, leadTimeDays = 14, safetyDays = 7) {
  return velocity30 * (leadTimeDays + safetyDays);
}

/* ─── LAST SALE DATE ──────────────────────────────────────────────── */

function lastSaleDate(orders, sku) {
  const normalSku = sku.trim().toUpperCase();
  let last = null;
  for (const o of orders) {
    if (o.cancelled_at) continue;
    const hasItem = (o.line_items || []).some(i => (i.sku || '').trim().toUpperCase() === normalSku);
    if (!hasItem) continue;
    const d = new Date(o.created_at);
    if (!last || d > last) last = d;
  }
  return last;
}

/* ─── MAIN PROCUREMENT TABLE ──────────────────────────────────────── */
// suppliers: { [sku]: { supplier, leadTimeDays, moq, costPrice, safetyDays } }

export function buildProcurementTable(inventoryMap, orders, suppliers = {}) {
  const rows = [];

  for (const [sku, inv] of Object.entries(inventoryMap)) {
    const sup = suppliers[sku] || {};

    // Velocity at multiple windows
    const vel7   = calcSalesVelocity(orders, sku, 7);
    const vel30  = calcSalesVelocity(orders, sku, 30);
    const vel90  = calcSalesVelocity(orders, sku, 90);

    // Prefer 30-day velocity for planning; fall back to 90-day if <14d of data
    const planVelocity = vel30 > 0 ? vel30 : vel90;

    const doi    = calcDaysOfInventory(inv.stock, planVelocity);
    const health = classifyStockHealth(doi, inv.stock);

    const leadTime   = sup.leadTimeDays ?? 14;
    const moq        = sup.moq ?? 0;
    const safetyDays = sup.safetyDays ?? 7;
    // Cost price: use supplier override if set; else estimate as 40% of selling price
    const costPrice  = sup.costPrice > 0 ? sup.costPrice : (inv.price * 0.4);

    const rop           = calcReorderPoint(planVelocity, leadTime, safetyDays);
    const shouldReorder = inv.stock <= rop && planVelocity > 0;
    const reorderQty    = calcReorderQty(planVelocity, moq, leadTime);

    // Revenue and volume
    const rev30  = calcSkuRevenue(orders, sku, 30);
    const rev90  = calcSkuRevenue(orders, sku, 90);
    const units30 = Math.round(vel30 * 30);

    // Inventory value
    const inventoryValue = inv.stock * (inv.price || 0);
    const costValue      = inv.stock * (costPrice || 0);

    // Dead stock detection
    const last        = lastSaleDate(orders, sku);
    const daysSinceSale = last ? Math.floor((Date.now() - last.getTime()) / 86400000) : 999;
    const isDead      = daysSinceSale > 90 && inv.stock > 0;

    // Priority score (lower = more urgent)
    let priority = 99;
    if (health === 'stockout') priority = 1;
    else if (health === 'critical' && shouldReorder) priority = 2;
    else if (health === 'critical') priority = 3;
    else if (health === 'low' && shouldReorder) priority = 4;
    else if (health === 'low') priority = 5;
    else if (isDead) priority = 7;
    else if (health === 'overstock') priority = 8;
    else priority = 6;

    rows.push({
      sku,
      title:          inv.title || sku,
      variantTitle:   inv.variantTitle || '',
      productType:    inv.productType || '',
      stock:          inv.stock,
      price:          inv.price,
      costPrice,
      inventoryValue,
      costValue,
      vel7,
      vel30,
      vel90,
      planVelocity,
      units30,
      doi,
      health,
      rop: Math.ceil(rop),
      shouldReorder,
      reorderQty,
      supplier:   sup.supplier || '',
      leadTime,
      moq,
      safetyDays,
      rev30,
      rev90,
      lastSaleDate: last,
      daysSinceSale,
      isDead,
      priority,
      estReorderCost: reorderQty * costPrice,
    });
  }

  // Sort: highest priority first, then by DOI asc
  rows.sort((a, b) => a.priority - b.priority || a.doi - b.doi);
  return rows;
}

/* ─── SUMMARY KPIs ────────────────────────────────────────────────── */

export function calcProcurementSummary(rows) {
  const active = rows.filter(r => r.stock > 0 || r.vel30 > 0);
  const totalValue    = rows.reduce((s, r) => s + r.inventoryValue, 0);
  const totalCostVal  = rows.reduce((s, r) => s + r.costValue, 0);
  const atRisk        = rows.filter(r => ['critical', 'stockout'].includes(r.health));
  const deadStock     = rows.filter(r => r.isDead);
  const toReorder     = rows.filter(r => r.shouldReorder);
  const overstock     = rows.filter(r => r.health === 'overstock');

  const doiVals = rows.filter(r => r.doi > 0 && r.doi < 999);
  const avgDoi  = doiVals.length > 0
    ? Math.round(doiVals.reduce((s, r) => s + r.doi, 0) / doiVals.length)
    : 0;

  const totalRev30 = rows.reduce((s, r) => s + r.rev30, 0);
  const estReorderTotal = toReorder.reduce((s, r) => s + r.estReorderCost, 0);

  return {
    totalSkus:         rows.length,
    activeSkus:        active.length,
    totalValue,
    totalCostVal,
    atRiskCount:       atRisk.length,
    atRiskValue:       atRisk.reduce((s, r) => s + r.inventoryValue, 0),
    deadStockCount:    deadStock.length,
    deadStockValue:    deadStock.reduce((s, r) => s + r.inventoryValue, 0),
    reorderCount:      toReorder.length,
    estReorderTotal,
    overstockCount:    overstock.length,
    overstockValue:    overstock.reduce((s, r) => s + r.inventoryValue, 0),
    avgDoi,
    totalRev30,
    stockoutCount:     rows.filter(r => r.health === 'stockout').length,
  };
}

/* ─── ABC ANALYSIS ────────────────────────────────────────────────── */

export function calcAbcAnalysis(rows, revenueKey = 'rev30') {
  const sorted = [...rows].sort((a, b) => (b[revenueKey] || 0) - (a[revenueKey] || 0));
  const totalRev = sorted.reduce((s, r) => s + (r[revenueKey] || 0), 0);

  let cumulative = 0;
  return sorted.map(r => {
    cumulative += r[revenueKey] || 0;
    const cumulativePercent = totalRev > 0 ? cumulative / totalRev : 0;
    const abc = cumulativePercent <= 0.80 ? 'A' : cumulativePercent <= 0.95 ? 'B' : 'C';
    return { ...r, abc, cumulativeRevenue: cumulative, cumulativePercent };
  });
}

/* ─── VELOCITY TRENDS ─────────────────────────────────────────────── */

// Returns daily units sold by SKU for sparkline charts (last 30 days)
export function buildDailyVelocity(orders, skus, days = 30) {
  const normalSkus = new Set(skus.map(s => s.trim().toUpperCase()));
  const cutoffMs   = Date.now() - days * 86400000;
  const dailyMap   = {}; // YYYY-MM-DD → { [sku]: qty }

  for (const o of orders) {
    if (o.cancelled_at) continue;
    const d = new Date(o.created_at);
    if (d.getTime() < cutoffMs) continue;
    const dateKey = d.toISOString().slice(0, 10);
    if (!dailyMap[dateKey]) dailyMap[dateKey] = {};
    for (const item of o.line_items || []) {
      const sku = (item.sku || '').trim().toUpperCase();
      if (!normalSkus.has(sku)) continue;
      dailyMap[dateKey][sku] = (dailyMap[dateKey][sku] || 0) + (parseInt(item.quantity) || 0);
    }
  }

  const dates = Object.keys(dailyMap).sort();
  return { dates, dailyMap };
}

/* ─── TOP MOVERS ──────────────────────────────────────────────────── */

export function getTopMovers(rows, n = 10) {
  return [...rows].sort((a, b) => b.vel30 - a.vel30).slice(0, n);
}

export function getSlowMovers(rows, n = 10) {
  return [...rows].filter(r => r.stock > 0).sort((a, b) => a.vel30 - b.vel30).slice(0, n);
}
